// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjmqOsYHL8UjK0QO5Mo70H5GNAY1lAuc',
    appId: '1:780200934923:web:ae86060093cbcc4280d10e',
    messagingSenderId: '780200934923',
    projectId: 'lastchance-be8f2',
    authDomain: 'lastchance-be8f2.firebaseapp.com',
    storageBucket: 'lastchance-be8f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dDMWmN1-CADV1XeyM1weYlv5b6AWgUU',
    appId: '1:780200934923:android:a992089ba105b94280d10e',
    messagingSenderId: '780200934923',
    projectId: 'lastchance-be8f2',
    storageBucket: 'lastchance-be8f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3V6zwEaGMt3m8v7AiYoF582R88SJKlgQ',
    appId: '1:780200934923:ios:a30056e0dc1bc73580d10e',
    messagingSenderId: '780200934923',
    projectId: 'lastchance-be8f2',
    storageBucket: 'lastchance-be8f2.appspot.com',
    iosClientId: '780200934923-867rcfkg5o3934h5bohagleed4l9jrlr.apps.googleusercontent.com',
    iosBundleId: 'com.firebase.hummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3V6zwEaGMt3m8v7AiYoF582R88SJKlgQ',
    appId: '1:780200934923:ios:a30056e0dc1bc73580d10e',
    messagingSenderId: '780200934923',
    projectId: 'lastchance-be8f2',
    storageBucket: 'lastchance-be8f2.appspot.com',
    iosClientId: '780200934923-867rcfkg5o3934h5bohagleed4l9jrlr.apps.googleusercontent.com',
    iosBundleId: 'com.firebase.hummy',
  );
}
